### ISSUE TITLE
Two images combined into one slide

### ISSUE THREAD

**Issue by megsfulton** [Automattic/stories-android#408] opened 2020-06-30 19:15 UTC
What happened:

- Created a story
- Selected media from device library 
- Published story
- Story failed on 5th slide (the image in this slide is not the same as the images that got combined), went through error handling flow
- Story published
- Last slide of story is a split screen showing the top half of slide 2 and the bottom half of slide 9 

Story:
https://particular-wildcat.jurassic.ninja/2020/06/30/57/

Slide 9:
https://particular-wildcat.jurassic.ninja/wp-content/uploads/2020/06/wp-15935438096194728231760037499830.jpg

Slide 2: 
https://particular-wildcat.jurassic.ninja/wp-content/uploads/2020/06/wp-15935438092171374647939649334563.jpg

What slide 9 should have been: 
https://drfranksbbq.files.wordpress.com/2020/06/wp-15932138678973735621791342293416.jpg

**Comment by mzorz** [comment] 2020-08-17 14:45
I haven't been able to reproduce this one but I have a strong feeling that in order to get such a weird result like this one, it's only due to reusing bitmaps and painting a Canvas half-way through as it looks like has been the case for this weird result.

If this is such a case, bitmaps are now being retained until only the output file has been saved since https://github.com/Automattic/stories-android/pull/491  - closing for now

**Closed by mzorz** 2020-08-17 14:45 UTC
Labels: Jurrasic ninja site
